name: Node JS Full CI CD Flow
on:
 push:
  branches:
    - master
  paths:
    - Fullcicd.yml
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - name: Install node JS version 12
     uses: actions/setup-node@v2
     with:
       node-version: "12"
   - name: Verify node version
     run: node --version
    
 Functional Testing:
  runs-on: ubuntu-latest
  needs: Build
  steps:
   - name: just echo
     run: |
      echo "Functional Testing"
      sleep 30
 
 Component-testing:
    runs-on: ubuntu-latest
    needs: Functional Testing
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Install the Libraries or Node Modules
        run: npm install

      - name: Perform Node.js Audit and Output to Json file
        run: npm audit --json >> node-audit-results.json
        continue-on-error: true

      - name: List the files available
        run: ls
      
      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: NodeAudit Output
          path: node-audit-results.json
        if: always()
        

 deployment:
    runs-on: ubuntu-latest
    needs: [Component-testing, frontend-static-scan]
    steps: 
      - name: Deployment Steps
        run: |
          echo "Deployment is going on"
          sleep 30
 frontend-static-scan:
    runs-on: ubuntu-latest
    needs: Functional Testing
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npm install -g retire

      - run: retire --outputformat json --outputpath retirejs-report.json --severity high
        continue-on-error: true

      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: RetireJS Output
          path: retirejs-report.json
        if: always()
     
  
 
