name: Node JS Full CI CD Flow
on: [push]
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - name: Install node JS version 12
     uses: actions/setup-node@v2
        with:
          node-version: "12"
  - name: Verify node version
    run: node --version
